FROM node:22-alpine AS base

LABEL maintainer="Ambiente node vite"
LABEL description="Ambiente de desenvolvimento Node.js para Vite"

WORKDIR /app

RUN npm install -g npm@latest --silent

FROM base AS dev

EXPOSE 5173

CMD ["sh", "-c", "if [ -f package.json ]; then npm install && npm run dev -- --host 0.0.0.0; else tail -f /dev/null; fi"]

FROM base AS prod

COPY . .

RUN if [ -f package.json ]; then npm install && npm run build; fi
RUN npm install -g serve --silent

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]
