FROM node:22-alpine AS base

LABEL maintainer="Ambiente node express"
LABEL description="Ambiente de desenvolvimento Node.js para Express"

WORKDIR /app

RUN npm install -g npm@latest --silent

FROM base AS dev

EXPOSE 3000

CMD ["sh", "-c", "if [ -f package.json ]; then npm install && (npm run dev || npm start); else tail -f /dev/null; fi"]

FROM base AS prod

COPY . .

RUN if [ -f package.json ]; then npm install --omit=dev; fi

EXPOSE 3000

CMD ["npm", "start"]
